@startuml
'https://plantuml.com/class-diagram

class App {
    - Frequency freq
    - App prog

    -readInput()
    -outputFreq(Frequency)
}
note right: Driver code
App <|-- Frequency

class Frequency {
    - TreeMap<String, Integer> freq

    + void addToMap(String)
    + gets()
}

@enduml