@startuml
'https://plantuml.com/class-diagram

class App {
    -Employees list

    - void readInput()
    - void sendOutput()
}

class Employees {
    -ArrayList<Person> employee

    + void processInput(String)
    + void addPerson(String, String, double)
    + void printTable()
}

class Person {
    - lastName
    - firstNAme
    - salary

    + void createPerson(String, String, double)
    + String getLastName()
    + String getFirstName()
    + double getSalary()
    + void setLastName()
    + void setFirstName()
    + void setSalary()
}

@enduml