@startuml
class App {
    + NameSorter sorter
    + App prog
      Driver code
    + readInput()
    + sendToList()
}

class NameSorter {
    - ArrayList names
    + addToList()
    + sortList()
    + printList()
}
@enduml